# Markdownlint configuration for Privacy Policy Analyzer documentation

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false
  html: false

# First line heading
MD041: false

# Multiple consecutive blank lines
MD012:
  maximum: 2

# Inline HTML
MD033: false

# Emphasis used instead of a header
MD036: false

# Lists without punctuation
MD032: false

# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029: false

# Code block language
MD040: false

# Horizontal rule style
MD035:
  style: "---"

# List indentation
MD007:
  indent: 2

# No bare URLs
MD034: false

# No hard tabs
MD010: false

# No trailing punctuation in headers
MD026: false

# No multiple spaces after hash on atx style header
MD020: false

# No multiple spaces before hash on atx style header
MD021: false

# Headers should be surrounded by blank lines
MD022: false

# Headers should start at the beginning of the line
MD023: false

# Multiple headers with the same content
MD024: false

# Link fragments
MD051: false
