repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: make mypy
        language: system
        pass_filenames: false

  # Documentation checks
  - repo: local
    hooks:
      - id: mkdocs-build
        name: MkDocs Build Check
        entry: uv run mkdocs build
        language: system
        files: \.(md|yml|yaml)$
        pass_filenames: false

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [ --fix, --config, .markdownlint.yaml ]
